### ISSUE TITLE
New design, colors, landing

### ISSUE THREAD

**Issue by pragmadash** [catberry/catberry-homepage#14]
- [x] Get rid of Semantic UI and implement simple light-weight styles for the homepage.
- [x] Add support for mobile devices (responsive design)
- [ ] Add background (paws, scratches, etc.) to make it more fun
- [ ] Choose a font

Implement a new landing page that has fancy animations for each Catberry's feature:

- [ ] Progressive Rendering – two browser pages and blocks appear on them, one of them using streaming, and the other one is using buffering (regular rendering)
- [ ] Isomorphic/Universal – four blocks: a server, RESTful API and a browser. Step by step, at the beginning the server renders HTML getting data from API, sends bundle.js to a browser and then the app works in a browser communicating with API directly.
- [ ] Cat-Components – browser page which is supposed to have a cat picture on it. All parts of the cat (head, paws, tail, body) are coming from the server and build the cat on the page
- [ ] Flux – one block – URI, another set of blocks – flux stores and component blocks. Parameters are extracted from URI, go to the stores, store blocks flush (trigger “changed”) and all bound component block flush as well (re-rendered)
- [ ] SEO – search bot comes to the grey page and then the page fills with orange and the bot goes away
- [ ] Production-ready – there is a rocket and a number. The number goes up to 90% and rocket becomes from red to green and then the rocket goes up.

**Comment by JuliaRechkunova** [comment]
Working branch https://github.com/catberry/catberry-homepage/tree/new-design
[x] Get rid of Semantic UI and implement simple light-weight styles for the homepage
[x] Add support for mobile devices (responsive design)
